[connections.supabase]
SUPABASE_URL = "https://btnxprliujsiasxkfcqb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0bnhwcmxpdWpzaWFzeGtmY3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjU1NzQyNjMsImV4cCI6MjA0MTE1MDI2M30.-i2wDE0mmGmrZWmEts2qNJE6mLrfEVwkfAnwBDOgAQs"